### ISSUE TITLE
Not getting trouble codes

### ISSUE THREAD

**Issue by JitenGoswami** [jeffmcfadden/CarDash#3]
Hello Jeff,
I am have been working so long to get trouble codes, but still i am not able to fetch any trouble codes from your present code.
Can you please help me by creating some sample code or anything else which is convenient to you, regarding getting a actual trouble codes from OBD device.
At present i am testing your code with OBD-2 ELM-327 wifi device.
Waiting for your feedback.

Regards,
Jiten

**Comment by jeffmcfadden** [comment]
Jiten,

I'm sorry, but this isn't something I'm going to be able to do any time soon. I simply don't have the time available to attempt to write and debug any code for this.

-- Jeff

**Comment by JitenGoswami** [comment]
Jeff,
Its fine i can understand. Thanks for your efforts.

But any guidance you can give me? As I need lot of research work but not getting any success.

Jiten

**Comment by jeffmcfadden** [comment]
I would start on Page 12 of the ELM AT documentation: https://www.elmelectronics.com/wp-content/uploads/2016/07//ELM323DS.pdf

Looks like you should be able to send a command of `01 01` to get a list of how many trouble codes/which PIDs have trouble codes set. You should be able to send a `04` mode command to reset the codes and lights as well.

Here are a few other sites to check out:
- https://learn.sparkfun.com/tutorials/obd-ii-uart-hookup-guide/obd-commands
- https://theksmith.com/software/hack-vehicle-bus-cheap-easy-part-1/
- http://mechanics.stackexchange.com/questions/8233/accessing-diagnostic-trouble-codes-dtcs-in-car
- http://blog.lemberg.co.uk/how-guide-obdii-reader-app-development

Cheers,

-- Jeff
